api/urls.py
from django.conf.urls import url, include
from api import views
from rest_framework import routers, reverse, response
from rest_framework import views as framework_views

# copied from https://stackoverflow.com/a/23321478/446391
class HybridRouter(routers.DefaultRouter):
    def __init__(self, *args, **kwargs):
        super(HybridRouter, self).__init__(*args, **kwargs)
        self._api_view_urls = {}
    def add_api_view(self, name, url):
        self._api_view_urls[name] = url
    def remove_api_view(self, name):
        del self._api_view_urls[name]
    @property
    def api_view_urls(self):
        ret = {}
        ret.update(self._api_view_urls)
        return ret

    def get_urls(self):
        urls = super(HybridRouter, self).get_urls()
        for api_view_key in self._api_view_urls.keys():
            urls.append(self._api_view_urls[api_view_key])
        return urls

    def get_api_root_view(self):
        # Copy the following block from Default Router
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, framework_viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)
        api_view_urls = self._api_view_urls

        class APIRoot(framework_views.APIView):
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {}
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse.reverse(url_name, request=request, format=format)
                # In addition to what had been added, now add the APIView urls
                for api_view_key in api_view_urls.keys():
                    ret[api_view_key] = reverse.reverse(api_view_urls[api_view_key].name, request=request, format=format)
                return response.Response(ret)

        return APIRoot.as_view()

# Create a router and register our viewsets with it.
router = HybridRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet, base_name='group')
router.register(r'staffgroups', views.StaffGroupViewSet, base_name='staffgroup')
router.register(r'userprofiles', views.UserProfileViewSet)
router.add_api_view('me', url(r'^me$', views.Me.as_view(), name='me'))

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
]

issues/urls.py
from django.conf.urls import patterns, url
from issues import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new$', views.create, name='create'),
    url(r'^(?P<issue_id>\d+)$', views.detail, name='detail'),
    url(r'^assigned/(?P<user_id>\d+)$', views.assigned, name='assigned'),
    url(r'^created/(?P<user_id>\d+)$', views.created, name='created'),
    url(r'^starred/(?P<user_id>\d+)$', views.starred, name='starred'),
]

sitconstaff/urls.py
from django.conf.urls import patterns, include, url
from sitconstaff.shortcuts import redirect_static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sitconstaff.views.home', name='home'),
    # url(r'^sitconstaff/', include('sitconstaff.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', 'core.views.index', name='index'),
    url(r'^favicon.ico$', redirect_static('img/SITCON.ico'), name='favicon'),
    url(r'^users$', 'users.views.default'), 
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^docs/', include('docs.urls', namespace='docs')),
    url(r'^issues/', include('issues.urls', namespace='issues')),
    url(r'^agenda/', include('agenda.urls', namespace='agenda')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^400$', 'django.views.defaults.bad_request'),
    url(r'^403$', 'django.views.defaults.permission_denied'),
    url(r'^404$', 'django.views.defaults.page_not_found'),
    url(r'^500$', 'django.views.defaults.server_error'),
    
    # Uncomment the next line to enable the admin:
    url(r'^backend/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^reg$', views.reg_list_token, name='reg_list_token'),
    url(r'^reg/add$', views.reg_add_token, name='reg_add_token'),
    url(r'^reg/edit/(?P<token>[0-9A-Za-z]+)$', views.reg_edit_token, name='reg_edit_token'),
    url(r'^reg/form/(?P<token>[0-9A-Za-z]+)$', views.reg_form, name='reg_form'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^new$', views.create, name='create'),
    url(r'^contacts$', views.contacts, name='contacts'),
    url(r'^contacts/export(?:/(?P<format>[0-9A-Za-z]+))?$', views.export, name='export'),
    url(r'^password/change$', views.change_password, name='change_password'),
    url(r'^password/reset$', views.reset_password, name='reset_password'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)$', views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^me$', views.me, name='me'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)$', views.profile, name='profile'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/team/(?P<tid>[0-9]+)$', views.team, name='team'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo$', views.photo.general, name='photo_general'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/small$', views.photo.small, name='photo_small'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/medium$', views.photo.medium, name='photo_medium'),
]

users/views/account.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.decorators.debug import sensitive_post_parameters, sensitive_variables
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import SetPasswordForm
from users.forms import PasswordResetForm
from users.token import parse_uid, check_token

@login_required
@sensitive_variables()
@sensitive_post_parameters()
def change_password(request):
    status = ''
    old_password = request.POST.get('old_password')
    new_password = request.POST.get('new_password')
    verify_password = request.POST.get('verify_password')
    if old_password and new_password and verify_password:
        if request.user.check_password(old_password):
            if new_password == verify_password:
                request.user.set_password(new_password)
                request.user.save()
                status = 'success'
            else: status = 'password_mismatch'
        else: status = 'invalid_login'
    return render(request, 'users/change_password.html', {'status': status})

def reset_password(request):
    form = PasswordResetForm()
    status = request.GET.get('status')

    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
    elif request.user.has_perm('auth.change_user'):        # Prefill user email
        try:
            user = User.objects.get(id=request.GET.get('id'))
            form = PasswordResetForm({'email': user.email})
        except User.DoesNotExist:
            pass

    if not status == 'invalid_token':
        status = None

    if form.is_valid():
        form.save()
        status = 'success'

    return render(request, 'users/reset_password.html', {'form': form, 'status': status})

@sensitive_post_parameters()
def reset_password_confirm(request, uidb64, token):
    user = parse_uid(uidb64)
    if user is not None and check_token(user, token):
        if request.method == 'POST':
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                return redirect(reverse('users:login') + '?status=reset_successful')
        else:
            form = SetPasswordForm(user)
    else:
        return redirect(reverse('users:reset_password') + '?status=invalid_token')

    return render(request, 'users/set_password.html', {'form': form})

users/views/create.py
 # -*- coding: utf-8 -*-

from django.conf import settings
from django.contrib.auth.decorators import permission_required
from django.contrib.auth.models import User, Group
from django.shortcuts import render
from django.views.decorators.debug import sensitive_variables
from notifications.utils import send_template_mail, format_address
from users.utils import generate_password, sorted_categories
from users.models import UserProfile

@sensitive_variables('password')
@permission_required('auth.add_user')
def create(request):
    errors = []
    status = ''

    if 'submit' in request.POST:
        user = User()

        username = request.POST.get('username')
        if username:
            if User.objects.filter(username=username).count() < 1:
                user.username = username
            else:
                errors += ['username', 'username_already_taken']
        else:
            errors += ['username', 'invalid_username']

        from django.core.validators import validate_email
        from django.core.exceptions import ValidationError
        email = request.POST.get('email')
        try:
            validate_email(email)

            if User.objects.filter(email=email).count() < 1:
                user.email = email
            else:
                errors += ['email', 'email_already_taken']

        except ValidationError:
            errors += ['email', 'invalid_email']

        user.first_name = request.POST.get('first_name')
        user.last_name = request.POST.get('last_name')

        password = generate_password()
        user.set_password(password)

        if len(errors) < 1:
            user.save()

            user.profile.title = request.POST.get('title')
            user.profile.display_name = request.POST.get('display_name')
            user.profile.school = request.POST.get('school')
            user.profile.bio = request.POST.get('bio')
            user.profile.grade = request.POST.get('grade')
            user.profile.phone = request.POST.get('phone')
            user.profile.comment = request.POST.get('comment')
            user.profile.save()

            for group_id in request.POST.getlist('groups'):
                try:
                    user.groups.add(Group.objects.get(id=group_id))
                except Group.DoesNotExist: pass

            user.save()        # Save the groups information

            if request.POST.get('send_welcome_letter'):
                context = {
                    'sender': request.user,
                    'receiver': user,
                    'password': password,
                    'groups': [g.name for g in user.groups.all()],
                }

                sender_address = format_address(request.user.profile.name, request.user.email)
                receiver_address = format_address(user.profile.name, user.email)
                send_template_mail(sender_address, receiver_address, 'mail/user_welcome.html', context)

            status = 'success'
        else:
            status = 'error'

    return render(request, 'users/create.html', {
        'categories': sorted_categories(),
        'errors': errors,
        'status': status,
    })

users/views/edit_profile.py
from django.shortcuts import render, get_object_or_404
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from users.models import *
from users.utils import validate_email

@login_required
def edit_profile(request, user):
	user = get_object_or_404(User, pk=id)
	
	if not (user == request.user or request.user.has_perm('auth.change_user')):
		return redirect(reverse('users:list'))
	
	errors = []
	status = ''

	if request.POST.get('submit'):
		profile = None
		try:
			profile = user.profile
		except UserProfile.DoesNotExist:
			profile = UserProfile(user=user)

		if request.user.has_perm('auth.change_user'):
			username = request.POST.get('username')
			if username != user.username:
				if username:
					if User.objects.filter(username=username).count() < 1:
						user.username = username
					else:
						errors += ['username', 'username_already_taken']
				else:
					errors += ['username', 'invalid_username']

			profile.title = request.POST.get('title')
		
		user.first_name = request.POST.get('first_name')
		user.last_name = request.POST.get('last_name')

		email = request.POST.get('email', '')
		if email != user.email:
			if validate_email(email):
				if User.objects.filter(email=email).count() < 1:
					user.email = email
				else:
					errors += ['email', 'email_already_taken']
			else:
				errors += ['email', 'invalid_email']

		profile.display_name = request.POST.get('display_name')
		profile.school = request.POST.get('school')
		profile.grade = request.POST.get('grade')
		profile.phone = request.POST.get('phone')
		profile.comment = request.POST.get('comment')

		if len(errors) < 1:
			user.save()
			profile.save()
			status = 'success'
		else:
			status = 'error'

	return render(request, 'users_edit_profile.html', {
		'u': user,
		'errors': errors,
		'status': status,
	})

users/views/photo.py
import re
from django.core.exceptions import ObjectDoesNotExist
from django.http import Http404, HttpResponseRedirect, HttpResponse
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.models import User
from django.template import Context, Template
from django.views.decorators.cache import cache_page
from core.api.decorators import api_endpoint
from core.imaging import resize_image
from users.models import UserProfile

@cache_page(60 * 60 * 24 * 14)
@api_endpoint(public=True)
def general(request, username_or_pk, size_p=None):
    size = size_p if size_p else 400
    size = int(request.GET.get('size')) if request.GET.get('size') else size
    if re.match(r'\d+', username_or_pk):
        try:
            profile = UserProfile.objects.get(user__pk=username_or_pk)
        except ObjectDoesNotExist:
            raise Http404('User with pk %d not found' % int(username_or_pk))
    else:
        try:
            profile = UserProfile.objects.get(user__username=username_or_pk)
        except ObjectDoesNotExist:
            raise Http404('User with username %s not found' % username_or_pk)

    if not profile.photo:
        return HttpResponseRedirect(profile.gravatar+'&s='+str(size))

    image_data, mime = resize_image(profile.photo, size=size)
    return HttpResponse(content=image_data, content_type=mime)

@api_endpoint(public=True)
def medium(request, username_or_pk):
    return general(request, username_or_pk, 400)

@api_endpoint(public=True)
def small(request, username_or_pk):
    return general(request, username_or_pk, 100)

users/views/profile.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.views import redirect_to_login
from django.conf import settings
from core.api.decorators import api_endpoint
from core.api.views import *
from users.models import GroupCategory

@login_required
@api_endpoint(public=True)
def profile(request, username):
    user = get_object_or_404(User, username=username)
    privileged = request.user.has_perm('auth.change_user')

    team_list = GroupCategory.objects.get(pk=settings.TEAM_GROUPCAT_ID).groups.all()
    same_team = any([user.groups.filter(pk__in=team_list).filter(pk=k.id).exists() for k in request.user.groups.filter(pk__in=team_list)])
    teamleader = any([user.profile.lead_team.filter(pk=k.id).exists() for k in request.user.groups.filter(pk__in=team_list)])

    if request.is_ajax():
        if user.is_active:
            return render_json(request, {
                'status': 'success',
                'user': {
                    'id': user.username,
                    'name': user.profile.name,
                    'title': user.profile.title,
                    'avatar': user.profile.avatar,
                }
            })
        return bad_request(request, {'status': 'invalid'})

    elif not request.user.is_authenticated():
        return redirect_to_login(request.path)

    return render(request, 'users/profile.html', {
        'u': user,
        'allow_phone': privileged or teamleader,
        'sensitive': user == request.user or request.user.has_perm('auth.change_user'),
        'privileged': privileged,
        'teams': filter(lambda x: x in user.groups.all(), team_list),
        'show_detail': user == request.user or privileged or request.user.has_perm('view_profile_detail'),
    })

@login_required
def me(request):
    return redirect('users:profile', request.user.username)

users/templates/users_change_password.html
{% extends 'core_main.html' %}
{% block title %}變更密碼{{ block.super }}{% endblock %}
{% block content %}
{% if status %}
<div class="radius {% if status == 'success' %}secondary{% else %}alert{% endif %} alert-box" data-alert>
	{% if status == 'invalid_login' %}密碼不正確，請再試一次。
	{% elif status == 'password_mismatch' %}新密碼不一致，請重新輸入。
	{% elif status == 'success' %}密碼變更成功。
	{% else %}發生不明錯誤，請回報行政組處理。（{{ status }}）{% endif %}
	<a href="#" class="close">&times;</a>
</div>
{% endif %}
<div class="row">
	<div class="large-6 small-9 small-centered columns">
		<div class="login-panel">
			<h3>變更密碼</h3>
			<form class="users-login" action="{% url 'users:change_password' %}" method="POST">
			{% csrf_token %}
				<div class="row"><div class="large-12 columns">
					<label for="old_password">目前密碼</label>
					<input type="password" id="old_password" name="old_password" size="30" required />
				</div></div>
				<div class="row"><div class="large-12 columns">
					<label for="new_password">新密碼</label>
					<input type="password" id="new_password" name="new_password" size="30" required />
				</div></div>
				<div class="row"><div class="large-12 columns">
					<label for="verify_password">再次輸入密碼</label>
					<input type="password" id="verify_password" name="verify_password" size="30" required />
				</div></div>
				<div class="row"><div class="large-12 columns">
					<input type="submit" name="submit" value="變更密碼" class="right secondary radius button" />
				</div></div>
			</form>
		</div>
	</div>
</div>
{% endblock %}

users/templates/users_contacts.html
{% extends 'core_main.html' %}
{% load usermeta %}
{% block title %}通訊錄{{ block.super }}{% endblock %}
{% block content %}
<div class="row">
	<div class="large-1 columns">
		<a class="right iconize icon-back has-tip" href="{% url 'users:list' %}" title="回到人員列表" data-tooltip></a>
	</div>
	<div class="large-9 columns">
		<h3>SITCON 工作人員通訊錄</h3>
		<table class="user-contacts main">
			<thead><tr>
				<th>職稱</th>
				<th>名稱</th>
				{% if show_details %}<th>電話</th>{% endif %}
				<th>Email</th>
			</tr></thead>
			<tbody>
			{% for u in users %}
			<tr>
				<td>{{ u.profile.title }}</td>
				<td><img class="avatar small" src="{{ u.email|get_avatar:'#' }}" alt="{{ u|get_name }}" />
					{{ u|get_name }}
				</td>
				{% if show_details %}
				<td>{% if u.profile.phone %}<a href="tel:{{ u.profile.phone }}">{{ u.profile.phone }}</a>{% endif %}</td>
				{% endif %}
				<td>{{ u.email|urlize }}</td>
			</tr>
			{% endfor %}
			</tbody>
		</table>
	</div>
	<div class="large-2 columns">
	</div>
</div>
{% endblock %}

users/templates/users_edit_profile.html
{% extends 'core_main.html' %}
{% load usermeta %}
{% block title %}編輯 ‧ {{ u|get_name }}{{ block.super }}{% endblock %}
{% block content %}
{% if status %}
<div class="radius {% if status == 'success' %}secondary{% else %}alert{% endif %} alert-box" data-alert>
	{% if status == 'success' %}{% if user == u %}你的{% endif %}個人檔案已經儲存。
	{% else %}儲存個人檔案時發生錯誤，請修正下列欄位。{% endif %}
	<a href="#" class="close">&times;</a>
</div>
{% endif %}
<div class="row">
	<div class="large-1 avatars columns">
		<img class="avatar medium has-tip" src="{{ u.email|get_avatar:'#' }}" alt="{{ u|get_name }}" title="請至 Gravatar 替換{% if user == u %}你的{% endif %}大頭照" data-tooltip />
		<a class="right iconize icon-back has-tip" href="{% url 'users:list' %}" title="回到人員列表"></a>
	</div>
	<div class="large-8 columns">
		<form action="{% url 'users:edit' u.username %}" method="POST" class="profile-main">
		{% csrf_token %}
			<div class="row">
				<div class="small-12 columns {% if 'username' in errors %}error{% endif %}">
				{% if perms.auth.change_user %}
					<input type="text" name="username" id="username" maxlength="30" placeholder="帳號" value="{{ u.username }}" required />
					{% if 'invalid_username' in errors %}<small>無效的帳號名稱。</small>
					{% elif 'username_already_taken' in errors %}<small>帳號名稱已被使用。</small>{% endif %}
				{% else %}
					<h4><span class="has-tip" title="請聯繫行政組以更改你的登入帳號">{{ u.username }}</span></h4>
				{% endif %}
				</div>
			</div>
			<div class="row">
				<div class="small-8 columns">
				{% if perms.auth.change_user %}
					<input type="text" name="title" maxlength="16" placeholder="職稱" value="{{ u.profile.title }}" />
				{% else %}
					<h5>{{ u.profile.title }}</h4>
				{% endif %}
				</div>
				<div class="small-4 columns">
				{% if user == u %}
					<a href="{% url 'users:change_password' %}" class="expand small secondary radius button">變更密碼</a>
				{% elif perms.auth.change_user %}
					<a href="{% url 'users:reset_password' %}?id={{ u.id }}" class="expand small secondary radius button">重設密碼</a>
				{% endif %}
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns">
					<input type="text" name="display_name" maxlength="16" placeholder="顯示名稱" value="{{ u.profile.display_name }}" />
				</div>
			</div>
			<div class="row">
				<div class="small-6 columns">
					<input type="text" name="last_name" maxlength="30" placeholder="姓" value="{{ u.last_name }}" />
				</div>
				<div class="small-6 columns">
					<input type="text" name="first_name" maxlength="30" placeholder="名" value="{{ u.first_name }}" />
				</div>
			</div>
			<div class="row">
				<div class="small-6 columns">
					<input type="text" name="school" maxlength="30" placeholder="學校" value="{{ u.profile.school }}" />
				</div>
				<div class="small-6 columns">
					<input type="text" name="grade" maxlength="30" placeholder="系所" value="{{ u.profile.grade }}" />
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns {% if 'email' in errors %}error{% endif %}">
					<input type="text" name="email" placeholder="電子郵件信箱" value="{{ u.email }}" required />
					{% if 'invalid_email' in errors %}<small>無效的電子郵件地址。</small>
					{% elif 'email_already_taken' in errors %}<small>電子郵件信箱已被使用。如須協助，請聯繫行政組。</small>{% endif %}
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns">
					<input type="text" name="phone" placeholder="電話號碼" value="{{ u.profile.phone }}" />
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns">
					<textarea name="comment" placeholder="備註">{{ u.profile.comment }}</textarea>
				</div>
			</div>
			<div class="button-row">
				<div class="right">
					<input type="submit" class="radius button" name="submit" value="更新" />
				</div>
			</div>
		</form>
	</div>
	<div class="large-3 columns">
	</div>
</div>
{% endblock %}

users/templates/users_list.html
{% extends 'core_main.html' %}
{% load usermeta %}
{% block title %}人員{{ block.super }}{% endblock %}
{% block content %}
<div class="row">
	<div class="large-9 columns">
		<ul class="user-list large-block-grid-4">
		{% for u in users %}
			<li class="user-item">
				<a href="{% url 'users:profile' u.username %}">
					<img class="avatar medium" src="{{ u.email|get_avatar:'#' }}" alt="{{ u|get_name }}" />
					<h4>{{ u|get_name }}</h4>
					<h4 class="subheader">{{ u.profile.title }}</h4>
				</a>
			</li>
		{% endfor %}
		</ul>
	</div>
	<div class="large-3 columns main-side-nav">
		<ul class="side-nav users-actions">
			{% if perms.auth.add_user %}<li><a href="{% url 'users:create' %}"><span class="icon-add iconize"></span> 新增人員</a></li>{% endif %}
			<li><a href="{% url 'users:edit' user.id %}"><span class="icon-profile iconize"></span> 編輯個人檔案</a></li>
			<li><a href="{% url 'users:contacts' %}"><span class="icon-contacts iconize"></span> 檢視通訊錄</a></li>
		</ul>
		<div class="divider"></div>
		{% for c in categories %}
			{% if c.is_visible or user.is_staff %}
			<h5>篩選{{ c.name }}</h5>
			<ul class="side-nav">
			{% for g in c.groups.all %}
				<li{% if filter == g.id %} class="active"{% endif %}><a href="{% url 'users:list' %}?g={{ g.id }}">{{ g.name }}</a></li>
			{% endfor %}
			</ul>
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}

users/templates/users_login.html
{% extends 'core_main.html' %}
{% block title %}登入{{ block.super }}{% endblock %}\
{% block content %}
{% if error %}
<div class="radius {% if error == 'invalid_login' %}alert{% else %}secondary{% endif %} alert-box" data-alert>
	{% if error == 'invalid_login' %}不正確的使用者或密碼。
	{% elif error == 'account_disabled' %}帳號已停用。請聯繫行政組以取得協助。
	{% elif error == 'reset_successful' %}密碼重設成功。請使用新密碼重新登入。
	{% else %}發生不明錯誤，請回報行政組處理。（{{ error }}）{% endif %}
	<a href="#" class="close">&times;</a>
</div>
{% endif %}
<div class="row">
	<div class="large-6 small-9 small-centered columns">
		<div class="login-panel">
			<h3>登入</h3>
			<form class="users-login" action="{% url 'users:login' %}" method="POST">
			{% csrf_token %}
				<div class="row"><div class="large-12 columns">
					<label for="username">使用者名稱</label>
					<input type="text" id="username" name="username" size="30" maxlength="30" required />
				</div></div>
				<div class="row"><div class="large-12 columns">
					<label for="password">密碼
						<a href="{% url 'users:reset_password' %}">（忘記密碼？）</a>
					</label>
					<input type="password" id="password" name="password" size="30" required />
				</div></div>
				<div class="row"><div class="large-12 columns">
					<input type="submit" name="submit" value="登入" class="right secondary radius button" />
				</div></div>
				{% if redirect_url %}
				<input type="hidden" name="next" value="{{ redirect_url }}" />
				{% endif %}
			</form>
		</div>
	</div>
</div>
{% endblock %}

users/templates/users_profile.html
{% extends 'core_main.html' %}
{% load usermeta %}
{% block title %}{{ u|get_name }}{{ block.super }}{% endblock %}
{% block content %}
<div class="row">
	<div class="large-3 columns">
		<img class="avatar large" src="{{ u.email|get_avatar:400 }}" alt="{{ u|get_name }}" />
		<h4>{{ u|get_name }}</h4>
		<h5 class="subheader">{{ u.profile.title }}</h5>
		<ul class="profile-meta">
			{% if u.profile.school %}<li><span class="icon-school iconize"></span> {{ u.profile.school }} {{ u.profile.grade }}</li>{% endif %}
			{% if u.profile.phone %}<li><span class="icon-phone iconize"></span> {{ u.profile.phone }}</li>{% endif %}
			{% if u.email %}<li><span class="icon-email iconize"></span> {{ u.email }}</li>{% endif %}
		</ul>
		<div class="profile-actions">
		{% if user == u or perms.auth.change_user %}
			<a href="{% url 'users:edit' u.username %}" class="small secondary radius button">編輯</a>
		{% endif %}
		</div>
	</div>
	<div class="large-5 columns">
		<h5 class="section-header"><a href="{% url 'issues:assigned' u.id %}">待辦事項</a></h5>
		<ul class="issue-list">
		</ul>
	</div>
	<div class="large-4 columns">
		<h5 class="section-header">參加的聚會</h5>
		<p></p>
	</div>
</div>
{% endblock %}