api/urls.py
from django.conf.urls import url, include
from api import views
from rest_framework import routers, reverse, response
from rest_framework import views as framework_views

# copied from https://stackoverflow.com/a/23321478/446391
class HybridRouter(routers.DefaultRouter):
    def __init__(self, *args, **kwargs):
        super(HybridRouter, self).__init__(*args, **kwargs)
        self._api_view_urls = {}
    def add_api_view(self, name, url):
        self._api_view_urls[name] = url
    def remove_api_view(self, name):
        del self._api_view_urls[name]
    @property
    def api_view_urls(self):
        ret = {}
        ret.update(self._api_view_urls)
        return ret

    def get_urls(self):
        urls = super(HybridRouter, self).get_urls()
        for api_view_key in self._api_view_urls.keys():
            urls.append(self._api_view_urls[api_view_key])
        return urls

    def get_api_root_view(self):
        # Copy the following block from Default Router
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, framework_viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)
        api_view_urls = self._api_view_urls

        class APIRoot(framework_views.APIView):
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {}
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse.reverse(url_name, request=request, format=format)
                # In addition to what had been added, now add the APIView urls
                for api_view_key in api_view_urls.keys():
                    ret[api_view_key] = reverse.reverse(api_view_urls[api_view_key].name, request=request, format=format)
                return response.Response(ret)

        return APIRoot.as_view()

# Create a router and register our viewsets with it.
router = HybridRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet, base_name='group')
router.register(r'staffgroups', views.StaffGroupViewSet, base_name='staffgroup')
router.register(r'userprofiles', views.UserProfileViewSet)
router.add_api_view('me', url(r'^me$', views.Me.as_view(), name='me'))

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
]

sitconstaff/urls.py
from django.conf.urls import patterns, include, url
from sitconstaff.shortcuts import redirect_static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sitconstaff.views.home', name='home'),
    # url(r'^sitconstaff/', include('sitconstaff.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', 'core.views.index', name='index'),
    url(r'^favicon.ico$', redirect_static('img/SITCON.ico'), name='favicon'),
    url(r'^users$', 'users.views.default'), 
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^docs/', include('docs.urls', namespace='docs')),
    url(r'^issues/', include('issues.urls', namespace='issues')),
    url(r'^agenda/', include('agenda.urls', namespace='agenda')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^400$', 'django.views.defaults.bad_request'),
    url(r'^403$', 'django.views.defaults.permission_denied'),
    url(r'^404$', 'django.views.defaults.page_not_found'),
    url(r'^500$', 'django.views.defaults.server_error'),
    
    # Uncomment the next line to enable the admin:
    url(r'^backend/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^reg$', views.reg_list_token, name='reg_list_token'),
    url(r'^reg/add$', views.reg_add_token, name='reg_add_token'),
    url(r'^reg/edit/(?P<token>[0-9A-Za-z]+)$', views.reg_edit_token, name='reg_edit_token'),
    url(r'^reg/form/(?P<token>[0-9A-Za-z]+)$', views.reg_form, name='reg_form'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^new$', views.create, name='create'),
    url(r'^contacts$', views.contacts, name='contacts'),
    url(r'^contacts/export(?:/(?P<format>[0-9A-Za-z]+))?$', views.export, name='export'),
    url(r'^password/change$', views.change_password, name='change_password'),
    url(r'^password/reset$', views.reset_password, name='reset_password'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)$', views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^me$', views.me, name='me'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)$', views.profile, name='profile'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/team/(?P<tid>[0-9]+)$', views.team, name='team'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo$', views.photo.general, name='photo_general'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/small$', views.photo.small, name='photo_small'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/medium$', views.photo.medium, name='photo_medium'),
]

issues/views/create.py
from django.shortcuts import render, redirect
from django.conf import settings
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required
from issues.models import Issue, IssueHistory, Label
from issues.utils import send_mail, parse_date
from users.mentions import filter_mentions
from users.utils import sorted_users

@permission_required('issues.add_issue')
def create(request):
    errors = []

    if 'submit' in request.POST:
        issue = Issue()
        issue.title = request.POST['title']
        issue.content = request.POST['content']
        issue.creator = request.user

        due_time = request.POST.get('due_time', '').strip()
        if len(due_time):
            try:
                due_time = parse_date(due_time)
                if due_time:
                    issue.due_time = due_time
                else:
                    errors.append('date-misformed')
            except ValueError:
                errors.append('date-invalid')

        assignee = request.POST.get('assignee')
        if assignee:    # Empty value => not assigned, no need to set
            try:
                issue.assignee = User.objects.get(id=assignee)
            except User.DoesNotExist:
                assignee = None        # Just in case we're under attack...

        labels = []
        for label_id in request.POST.getlist('labels'):
            try:
                labels.append(Label.objects.get(id=label_id))
            except Label.DoesNotExist: pass

        if not errors:
            issue.save()    # Need to save before we can enforce N to N relationship
            issue.starring.add(request.user)    # Auto watch

            # Add or remove labels has history so we don't worry on history creation
            issue.labels.add(*labels)

            mentions, _ = filter_mentions(issue.content)
            if assignee:
                mentions.add(issue.assignee)
            mentions.discard(request.user)

            for user in mentions:
                issue.starring.add(user)    # Auto watch
                send_mail(request.user, user, 'mail/issue_created.html', { 'issue': issue })

            # Broadcast new issues automatically
            send_mail(request.user, settings.BROADCAST_EMAIL, 'mail/issue_created.html', { 'issue': issue })

            if assignee:
                IssueHistory.objects.create(issue=issue, user=request.user,
                                            mode=IssueHistory.ASSIGN, content=assignee)

            if due_time:
                IssueHistory.objects.create(issue=issue, user=request.user,
                                            mode=IssueHistory.SET_DUE, content=due_time)

            return redirect('issues:detail', issue.id)

    return render(request, 'issues/create.html', {
        'labels': Label.objects.all(),
        'users': sorted_users(User.objects.filter(is_active=True)),
        'errors': errors,
    })

issues/views/list.py
from django.shortcuts import render
from django.contrib.auth.decorators import login_required
from core.api.decorators import api_endpoint, ajax_required
from core.api.views import *
from issues.models import Issue, Label

@api_endpoint
@ajax_required(redirect_url='issues:list')
def ajax(request):
    return not_implemented(request, {'error': 'not_implemented'})

@login_required
def list(request, filter=None):
    if not request.user.profile.is_authorized():
        dataset = request.user.assigned_issues.all()
        dataset = dataset | request.user.created_issues.all()
    else:
        dataset = Issue.objects

    counts = {
        'all': Issue.objects.count(),
    }

    # 1st phase filtering
    if not filter: filter = {}
    if 'assignee' in filter:
        dataset = dataset.filter(assignee__id=filter['assignee'])
    if 'creator' in filter:
        dataset = dataset.filter(creator__id=filter['creator'])
    if 'starring' in filter:
        dataset = dataset.filter(starring__id=filter['starring'])

    # 1st phase counting
    counts['open'] = dataset.filter(is_open=True).count()
    counts['closed'] = dataset.filter(is_open=False).count()

    # 2nd phase parameter parsing
    filter['is_open'] = not (request.GET.get('state') == 'closed')

    label = request.GET.get('label')
    if label and str(label).isdigit():
        filter['label'] = label

    sort_order = request.GET.get('direction')
    if request.GET.get('sort') == 'due':
        filter['due_time'] = '-' if sort_order == 'desc' else '+'
    else:
        filter['creation_time'] = '+' if sort_order == 'asc' else '-'

    # 2nd phase filtering
    dataset = dataset.filter(is_open=filter['is_open'])
    if 'label' in filter:
        dataset = dataset.filter(labels__id=filter['label'])
    if 'due_time' in filter:
        dataset = dataset.order_by('due_time' if filter['due_time'] == '+' else '-due_time')
    if 'creation_time' in filter:
        dataset = dataset.order_by('creation_time' if filter['creation_time'] == '+' else '-creation_time')

    return render(request, 'issues/list.html', {
        'issues': dataset.all(),
        'labels': Label.objects.all(),
        'filter': filter,
        'counts': counts,
    })

@login_required
def assigned(request, user_id):
    return list(request, {'assignee': user_id})

@login_required
def created(request, user_id):
    return list(request, {'creator': user_id})

@login_required
def starred(request, user_id):
    return list(request, {'starring': user_id})

notifications/views/create.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required
from notifications.utils import format_address, parse_address, send_template_mail

@permission_required('notifications.add_message')
def create(request):
    context = {}

    if request.POST.get('submit'):

        if request.POST.get('method') == 'sms':
            pass

        sender = ''
        receivers = {}

        if request.POST.get('sender_email'):
            sender = format_address(request.POST.get('sender_name'), request.POST.get('sender_email'))

        receiver_target = request.POST.get('receiver', '').split(',')
        if 'staff' in receiver_target:
            for user in User.objects.exclude(email='', is_active=False):
                receivers[user.email] = user.profile.name

        if request.POST.get('receivers'):
            additional_receivers = request.POST.get('receivers').strip().split('\n')
            for entry in additional_receivers:
                if ':' in entry:
                    name, addr = parse_address(entry)
                    receivers[addr] = name
                else:
                    receivers[entry] = ''

        # TODO: Reimplement batch sending
        for email, name in receivers.items():
            send_template_mail(
                sender,
                format_address(name, email),
                'mail/notification_general.html',
                {
                    'subject': request.POST.get('subject'),
                    'content': request.POST.get('content'),
                    'reply_to': request.POST.get('reply_address'),
                }
            )

        context['status'] = 'success'

    return render(request, 'notifications/create.html', context)

notifications/views/list.py
from django.shortcuts import render
from django.contrib.auth.decorators import permission_required
from notifications.models import Message

@permission_required('notifications.add_message')
def list(request):
    context = {
        'messages': Message.objects.filter(is_sent=False),
    }
    return render(request, 'notifications/list.html', context)

submission/views/create.py
from django.shortcuts import render
from django.contrib.auth.models import User
from django.contrib.auth.decorators import permission_required
from django.conf import settings
from django.core.exceptions import ValidationError
from django.shortcuts import redirect
from django.http import Http404
from submission.forms import SubmissionForm
from submission.forms import SubmissionFileForm
from core.formatting import render_document
from core.settings.base import SUBMISSION_END
from docs.node import Node
import datetime

@permission_required('submission.add_submission')
def create(request):
    if SUBMISSION_END < datetime.datetime.now():
        raise Http404
    context = {
            'user': request.user,
            'rule': render_document(Node(nid=settings.SUBMISSION_RULE_DOCID).model.current_revision.text.text)
            }

    if request.POST.get('submit'):
        sub = SubmissionForm(request.POST, request.FILES)

        if sub.is_valid():
            submission = sub.save(commit=False)
            submission.user = request.user
            submission.save()

            for f in request.FILES.getlist('slide'):
                form = SubmissionFileForm().save(commit=False)
                form.submission = submission
                form.file = f
                form.save()

            return redirect('submission:list')
        else:
            raise ValidationError(sub.errors.as_data())

    return render(request, 'submission/create.html', context)

users/views/account.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.views.decorators.debug import sensitive_post_parameters, sensitive_variables
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
from django.contrib.auth.forms import SetPasswordForm
from users.forms import PasswordResetForm
from users.token import parse_uid, check_token

@login_required
@sensitive_variables()
@sensitive_post_parameters()
def change_password(request):
    status = ''
    old_password = request.POST.get('old_password')
    new_password = request.POST.get('new_password')
    verify_password = request.POST.get('verify_password')
    if old_password and new_password and verify_password:
        if request.user.check_password(old_password):
            if new_password == verify_password:
                request.user.set_password(new_password)
                request.user.save()
                status = 'success'
            else: status = 'password_mismatch'
        else: status = 'invalid_login'
    return render(request, 'users/change_password.html', {'status': status})

def reset_password(request):
    form = PasswordResetForm()
    status = request.GET.get('status')

    if request.method == 'POST':
        form = PasswordResetForm(request.POST)
    elif request.user.has_perm('auth.change_user'):        # Prefill user email
        try:
            user = User.objects.get(id=request.GET.get('id'))
            form = PasswordResetForm({'email': user.email})
        except User.DoesNotExist:
            pass

    if not status == 'invalid_token':
        status = None

    if form.is_valid():
        form.save()
        status = 'success'

    return render(request, 'users/reset_password.html', {'form': form, 'status': status})

@sensitive_post_parameters()
def reset_password_confirm(request, uidb64, token):
    user = parse_uid(uidb64)
    if user is not None and check_token(user, token):
        if request.method == 'POST':
            form = SetPasswordForm(user, request.POST)
            if form.is_valid():
                form.save()
                return redirect(reverse('users:login') + '?status=reset_successful')
        else:
            form = SetPasswordForm(user)
    else:
        return redirect(reverse('users:reset_password') + '?status=invalid_token')

    return render(request, 'users/set_password.html', {'form': form})

users/templates/users/contacts.html
{% extends 'core/master.html' %}
{% block title %}通訊錄{{ block.super }}{% endblock %}
{% block content %}
<div class="row">
	<div class="large-1 columns">
		<a class="right iconize icon-back has-tip" href="{% url 'users:list' %}" title="回到人員列表" data-tooltip></a>
	</div>
	<div class="large-{{ show_details|yesno:'11,9' }} columns">
		<h3>{{ site.title }} 工作人員通訊錄</h3>
		<table class="user-contacts main">
			<thead><tr>
				<th>職稱</th>
				<th>名稱</th>
				{% if show_details %}
				<th>本名</th>
				<th>學校</th>
				{% endif %}
				{% if authorized %}
				<th>電話</th>
				{% endif %}
				<th>Email</th>
			</tr></thead>
			<tbody>
			{% for u in users %}
			<tr>
				<td>{{ u.profile.title }}</td>
				<td>
					<img class="avatar small" src="{{ u.profile.avatar }}" alt="{{ u.profile.name }}" />
					<a href="{% url 'users:profile' u.username %}">{{ u.profile.name }}</a>
				</td>
				{% if show_details %}
				<td>{{ u.last_name }} {{ u.first_name }}</td>
				<td>{{ u.profile.school }} {{ u.profile.grade|truncatechars:12 }}</td>
				{% endif %}
				{% if authorized %}
				<td>{% if u.profile.phone %}<a href="tel:{{ u.profile.phone }}">{{ u.profile.phone }}</a>{% endif %}</td>
				{% endif %}
				<td>{{ u.email|urlize }}</td>
			</tr>
			{% endfor %}
			</tbody>
		</table>
		<ul class="user-export-options inline-list">
			<li>匯出：</li>
			<li><a href="{% url 'users:export' 'html' %}">HTML</a></li>
			<li><a href="{% url 'users:export' 'csv' %}">CSV</a></li>
			<li><a href="{% url 'users:export' 'xml' %}">XML</a></li>
			<li><a href="{% url 'users:export' 'vcard' %}">vCard</a></li>
		</ul>
	</div>
	{% if not show_details %}
	<div class="large-2 columns">
	</div>
	{% endif %}
</div>
{% endblock %}

users/templates/users/list.html
{% extends 'core/master.html' %}
{% block title %}人員{{ block.super }}{% endblock %}
{% block content %}
<div class="row">
	<div class="large-9 columns">
		<ul class="user-list large-block-grid-4">
		{% for u, privileged, groups in users %}
			<li class="user-item">
				<a href="{% url 'users:profile' u.username %}">
					<img class="avatar medium" src="{{ u.profile.avatar }}" alt="{{ u.profile.name }}" />
					<div><h4 style="display: inline-block;">{{ u.profile.name }}</h4> {% if privileged or u == user %}<a href="{% url 'users:edit' u.username %}"><span class="icon-edit iconize" ></span></a>{% endif %} {% if teamleader or privileged %}<a href="#" data-dropdown="select_team_{{ u.username }}" data-default-content="選取組別"><span class="icon-add iconize" ></span></a>{% endif %}</div>
					<h4 class="subheader">{% for g in groups %}<span class="radius secondary label" name="{{ g.id }}">{{ g.name }}</span>{% if not forloop.last %} {% endif %}{% endfor %}</h4>
					<ul id="select_team_{{ u.username }}" class="f-dropdown with-ticks team_selector" name="{{ u.username }}" data-dropdown-content>
						{% for t in teams %}
						<li><label for="{{ u.username }}_group_{{ t.id }}_checkbox"><input type="checkbox" class="team_checkbox" id="{{ u.username }}_group_{{ t.id }}_checkbox" name="{{ u.username }}_groups" value="{{ t.id }}" data-label="{{ t.name }}" {% if t in groups %}checked{% endif %} {% if t not in user.profile.lead_team.all and not privileged %}disabled{% endif %} />{{ t.name }}</label></li>
						{% endfor %}
					</ul>
				</a>
			</li>
		{% endfor %}
		</ul>
	</div>
	<div class="large-3 columns main-side-nav">
		<ul class="side-nav users-actions">
			{% if perms.auth.add_user %}<li><a href="{% url 'users:reg_list_token' %}"><span class="icon-add iconize"></span> 登錄系統</a></li>{% endif %}
			<li><a href="{% url 'users:edit' user.username %}"><span class="icon-profile iconize"></span> 編輯個人檔案</a></li>
			<li><a href="{% url 'users:contacts' %}?{{ query_string }}"><span class="icon-contacts iconize"></span> 檢視通訊錄</a></li>
		</ul>
		<div class="divider"></div>
		{% for c, groups in categories.items %}
			{% if c.is_visible or user.is_staff %}
			<h5>篩選{{ c.name }}</h5>
			<ul class="side-nav">
			{% for g in groups %}
				<li{% if g.id in filters %} class="active"{% endif %}><a href="{% url 'users:list' %}?g={{ g.id }}">{{ g.name }}</a></li>
			{% endfor %}
			</ul>
			{% endif %}
		{% endfor %}
		{% if perms.auth.add_user or perms.auth.change_user %}
			<h5>異次元<span class="has-tip" title="供行政組維護帳號使用">™</span></h5>
			<ul class="side-nav">
				<li{% if 'disabled' in filters %} class="active"{% endif %}><a href="{% url 'users:list' %}?find=disabled">停用的帳號</a></li>
				<li{% if 'non_staff' in filters %} class="active"{% endif %}><a href="{% url 'users:list' %}?find=non_staff">非工作人員帳號</a></li>
				<li{% if 'all' in filters %} class="active"{% endif %}><a href="{% url 'users:list' %}?find=all">所有帳號</a></li>
			</ul>
		{% endif %}
		<div class="divider"></div>
			<h5>匯出</h5>
			<ul class="side-nav">
				<li><a href="{% url 'users:export' 'html' %}?{{ params }}">HTML</a></li>
				<li><a href="{% url 'users:export' 'csv' %}?{{ params }}">CSV</a></li>
				<li><a href="{% url 'users:export' 'xml' %}?{{ params }}">XML</a></li>
				<li><a href="{% url 'users:export' 'vcard' %}?{{ params }}">vCard</a></li>
			</ul>
	</div>
</div>
{% endblock %}


{% block scripts %}
<script type="text/javascript">
$('.team_selector').on('change', '.team_checkbox', function() {
	uid = $(this).parents('.team_selector').attr('name');
	tid = $(this).val();
	team_name = $(this).attr('data-label');
	subheader = $(this).parents('ul').siblings('.subheader')
	state = $(this).is(":checked");
	$.ajax({
		type: 'POST',
		url: '/users/' + uid + '/team/' + tid,
		data: {data: state},
		success: function (data) {
			subheader.html(data.map(function(g) { return '<span class="radius secondary label" name="' + g['id'] + '">' + g['name'] + '</span>'; }).join())
		},
		error: function (data) {}
	})
});
</script>
{% endblock %}

users/templates/users/reg_edit_token.html
{% extends 'core/master.html' %}
{% block title %}登錄 Token 新增{{ block.super }}{% endblock %}
{% block content %}
{% if status %}
<div class="radius {% if status == 'success' %}secondary{% else %}alert{% endif %} alert-box" data-alert>
	{% if status == 'success' %}Token 編輯成功。
	{% else %}儲存資料時發生錯誤，請修正下列欄位。{% endif %}
	<a href="#" class="close">&times;</a>
</div>
{% endif %}
<div class="row">
	<div class="large-1 avatars columns">
		<a class="right iconize icon-back has-tip" href="{% url 'users:reg_list_token' %}" title="回到 Token 列表" data-tooltip></a>
	</div>
	<div class="large-8 columns">
		<form action="{% url 'users:reg_edit_token' token.token %}" method="POST" class="profile-main">
			{% csrf_token %}
			<div class="row field-header">
				<div class="small-12 columns">
					<h6>Edit Token <small>{{ token.token }}</small></h6>
				</div>
			</div>
			<div class="row">
				<div class="small-6 columns">
					<label for="display_name">暱稱
						<input type="text" id="display_name" name="display_name" value="{{ token.display_name }}"/></label>
				</div>
				<div class="small-6 columns">
					<label for="email">電子郵件
						<input type="text" id="email" name="email" value="{{ token.email }}"/></label>
				</div>
			</div>
			<div class="row">
				<div class="small-6 columns">
					<label for="username">使用者名稱
						<input type="text" id="username" name="username" value="{{ token.username }}"/></label>
				</div>
			</div>
			<div class="row">
				<div class="small-12 columns">
					<label class="inline"><a href="#" id="groups_label" class="has-tip" title="設定權限" data-tooltip data-dropdown="groups_dropdown" data-default-content="選取組別">選取組別</a></label>
					<ul id="groups_dropdown" class="f-dropdown with-ticks" data-dropdown-content>
						{% for c, groups in categories.items %}
						<h6>{{ c.name }}</h6>
						{% for g in groups %}
						<li><label for="group_{{ g.id }}_checkbox"><input type="checkbox" class="group_checkbox" id="group_{{ g.id }}_checkbox" name="groups" value="{{ g.id }}" data-label="{{ g.name }}" {% if g in token.groups.all %} checked {% endif %}/>{{ g.name }}</label></li>
						{% endfor %}
						{% endfor %}
					</ul>
				</div>
			</div>
			<div class="row">
				<div class="small-8 columns">
					<label for="valid">Valid Token:
						<input type="checkbox" value="True" name="valid" id="valid" {% if token.valid %} checked {% endif %}/>
					</label>
				</div>
			</div>
			<div class="button-row">
				<div class="right">
					<input type="submit" class="radius button" name="submit" value="編輯 Token" />
				</div>
			</div>
		</form>
	</div>
	<div class="large-3 columns text">
	</div>
</div>
{% endblock %}
{% block scripts %}
<script type="text/javascript">
$(document).ready(function() {
	$('.group_checkbox').change(function() {
		var sel = [];
		$('.group_checkbox:checked').each(function (index,e) {
			sel.push($.trim($(e).data('label')));
		});
		$('#groups_label').text(sel.length ? sel.join('、') : $('#groups_label').data('default-content'));
	});
});
</script>
{% endblock %}

users/templates/users/reg_list_token.html
{% extends 'core/master.html' %}
{% block title %}登錄系統{{ block.super }}{% endblock %}
{% block content %}
<div class="row">
	<div class="large-9 columns">
		<table class="large-12" style="table-layout: fixed;">
			<tr>
				<td class="large-2">Token</td>
				<td class="large-2">username</td>
				<td class="large-3">暱稱</td>
				<td class="large-3">組別</td>
				<td class="large-2">狀態</td>
			</tr>
		{% for t in tokens %}
			<tr style="font-size: 85%;">
				<td style="overflow: hidden;"><a href="{% url 'users:reg_edit_token' t.token %}"><span class="icon-edit iconize" ></span></a><a href="{% url 'users:reg_form' t.token %}" ><span>{{ t.token }}</span></a></td>
		<td style="overflow: hidden;">{{ t.username }}</td>
                <td style="overflow: hidden;">{{ t.name }}</td>
				<td>{% for g in t.groups.all %}{{ g.name }}{% if not forloop.last %}, {% else %}{% endif %}{% endfor %}</td>
				<td style="overflow: hidden;">{% if not t.user and t.valid %}已啟用{% elif t.user %}已被 <a href="{% url 'users:profile' t.user.username %}">{{ t.user.username }}</a> 註冊 {% else %}未啟用{% endif %}</td>
			</tr>
		{% endfor %}
		</table>
	</div>
	<div class="large-3 columns main-side-nav">
		<ul class="side-nav users-actions">
			<li><a href="{% url 'users:reg_add_token' %}" class="radius button" style="color: #fff;">新增 Token</a></li>
		</ul>
		<div class="divider"></div>
		{% for c, groups in categories.items %}
			{% if c.is_visible or user.is_staff %}
			<h5>篩選{{ c.name }}</h5>
			<ul class="side-nav">
			{% for g in groups %}
				<li{% if g.id in filters %} class="active"{% endif %}><a href="{% url 'users:reg_list_token' %}?g={{ g.id }}">{{ g.name }}</a></li>
			{% endfor %}
				<li{% if 'disabled' in filters %} class="active"{% endif %}><a href="{% url 'users:reg_list_token' %}?find=disabled">停用的 Token</a></li>
				<li{% if 'all' in filters %} class="active"{% endif %}><a href="{% url 'users:reg_list_token' %}?find=all">全部 Token</a></li>
			</ul>
			{% endif %}
		{% endfor %}
	</div>
</div>
{% endblock %}