agenda/urls.py
from django.conf.urls import patterns, url
from agenda import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
]

api/urls.py
from django.conf.urls import url, include
from api import views
from rest_framework import routers, reverse, response
from rest_framework import views as framework_views

# copied from https://stackoverflow.com/a/23321478/446391
class HybridRouter(routers.DefaultRouter):
    def __init__(self, *args, **kwargs):
        super(HybridRouter, self).__init__(*args, **kwargs)
        self._api_view_urls = {}
    def add_api_view(self, name, url):
        self._api_view_urls[name] = url
    def remove_api_view(self, name):
        del self._api_view_urls[name]
    @property
    def api_view_urls(self):
        ret = {}
        ret.update(self._api_view_urls)
        return ret

    def get_urls(self):
        urls = super(HybridRouter, self).get_urls()
        for api_view_key in self._api_view_urls.keys():
            urls.append(self._api_view_urls[api_view_key])
        return urls

    def get_api_root_view(self):
        # Copy the following block from Default Router
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, framework_viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)
        api_view_urls = self._api_view_urls

        class APIRoot(framework_views.APIView):
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {}
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse.reverse(url_name, request=request, format=format)
                # In addition to what had been added, now add the APIView urls
                for api_view_key in api_view_urls.keys():
                    ret[api_view_key] = reverse.reverse(api_view_urls[api_view_key].name, request=request, format=format)
                return response.Response(ret)

        return APIRoot.as_view()

# Create a router and register our viewsets with it.
router = HybridRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet, base_name='group')
router.register(r'staffgroups', views.StaffGroupViewSet, base_name='staffgroup')
router.register(r'userprofiles', views.UserProfileViewSet)
router.add_api_view('me', url(r'^me$', views.Me.as_view(), name='me'))

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
]

core/urls.py
from django.conf.urls import patterns, include, url
from core.shortcuts import redirect_static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = [
    # Examples:
    # url(r'^$', 'roboconf.views.home', name='home'),
    # url(r'^roboconf/', include('roboconf.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', 'core.views.index', name='index'),
    url(r'^favicon.ico$', redirect_static('img/SITCON.ico'), name='favicon'),
    url(r'^users$', 'users.views.default'),
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^issues/', include('issues.urls', namespace='issues')),
    url(r'^agenda/', include('agenda.urls', namespace='agenda')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^api/', include('api.urls')),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),# not used since we don't need authentication to access API
    url(r'^o/', include('oauth2_provider.urls', namespace='oauth2_provider')),
    url(r'^400$', 'django.views.defaults.bad_request'),
    url(r'^403$', 'django.views.defaults.permission_denied'),
    url(r'^404$', 'django.views.defaults.page_not_found'),
    url(r'^500$', 'django.views.defaults.server_error'),

    # Uncomment the next line to enable the admin:
    url(r'^backend/', include(admin.site.urls)),
]

issues/urls.py
from django.conf.urls import patterns, url
from issues import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^new$', views.create, name='create'),
    url(r'^(?P<issue_id>\d+)$', views.detail, name='detail'),
    url(r'^assigned/(?P<user_id>\d+)$', views.assigned, name='assigned'),
    url(r'^created/(?P<user_id>\d+)$', views.created, name='created'),
    url(r'^starred/(?P<user_id>\d+)$', views.starred, name='starred'),
]

sitconstaff/urls.py
from django.conf.urls import patterns, include, url
from sitconstaff.shortcuts import redirect_static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sitconstaff.views.home', name='home'),
    # url(r'^sitconstaff/', include('sitconstaff.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', 'core.views.index', name='index'),
    url(r'^favicon.ico$', redirect_static('img/SITCON.ico'), name='favicon'),
    url(r'^users$', 'users.views.default'), 
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^docs/', include('docs.urls', namespace='docs')),
    url(r'^issues/', include('issues.urls', namespace='issues')),
    url(r'^agenda/', include('agenda.urls', namespace='agenda')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^400$', 'django.views.defaults.bad_request'),
    url(r'^403$', 'django.views.defaults.permission_denied'),
    url(r'^404$', 'django.views.defaults.page_not_found'),
    url(r'^500$', 'django.views.defaults.server_error'),
    
    # Uncomment the next line to enable the admin:
    url(r'^backend/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^reg$', views.reg_list_token, name='reg_list_token'),
    url(r'^reg/add$', views.reg_add_token, name='reg_add_token'),
    url(r'^reg/edit/(?P<token>[0-9A-Za-z]+)$', views.reg_edit_token, name='reg_edit_token'),
    url(r'^reg/form/(?P<token>[0-9A-Za-z]+)$', views.reg_form, name='reg_form'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^new$', views.create, name='create'),
    url(r'^contacts$', views.contacts, name='contacts'),
    url(r'^contacts/export(?:/(?P<format>[0-9A-Za-z]+))?$', views.export, name='export'),
    url(r'^password/change$', views.change_password, name='change_password'),
    url(r'^password/reset$', views.reset_password, name='reset_password'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)$', views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^me$', views.me, name='me'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)$', views.profile, name='profile'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/team/(?P<tid>[0-9]+)$', views.team, name='team'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo$', views.photo.general, name='photo_general'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/small$', views.photo.small, name='photo_small'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/medium$', views.photo.medium, name='photo_medium'),
]

notifications/models.py
from django.db import models
from django.utils import timezone

import threading


class Message(models.Model):
    EMAIL = '@'
    SMS = '+'
    METHOD_CHOICES = (
        (EMAIL, 'E-Mail'),
        (SMS, 'SMS'),
    )

    method = models.CharField(max_length=1, choices=METHOD_CHOICES, default=EMAIL)
    sender = models.CharField(max_length=160, blank=True, default='')    # In sender & receiver field,
    receiver = models.CharField(max_length=160)        # use ':' to separate between name and address/number
    subject = models.CharField(max_length=128)
    content = models.TextField()
    creation_time = models.DateTimeField(editable=False, default=timezone.now)
    is_sent = models.BooleanField(default=False)

    def __str__(self):
        return "%s[%s] %s" % (self.method, self.receiver, self.subject)

    def save(self, *args, **kwargs):
        super(Message, self).save(*args, **kwargs)
        threading.Thread(target=self.send).start()

    def send(self, **kwargs):
        if self.method == Message.EMAIL:
            import traceback
            import notifications.utils as utils
            from django.conf import settings
            from django.core import mail
            from django.utils import html

            email = mail.EmailMultiAlternatives(self.subject, connection=kwargs.get('connection'))
            email.from_email = utils.to_email_address(self.sender or settings.DEFAULT_NOTIFICATION_SENDER)
            email.to = [utils.to_email_address(self.receiver)]
            email.body = html.strip_tags(self.content)
            email.attach_alternative(self.content, 'text/html')

            try:
                email.send()
            except:
                print('Failed to send email')
                traceback.print_exc()
            else:
                self.is_sent = True
                super(Message, self).save()

        elif self.method == Message.SMS:
            from notifications.sms import SmsMessage

            sms = SmsMessage()
            sms.to = self.receiver
            sms.text = self.content

            if self.sender:
                sms.from_sender = self.sender

            self.is_sent = sms.send()
            super(Message, self).save()

core/api/views.py
import json
from django import http

def parse_json(request):
    try:
        return json.load(request)
    except ValueError:
        return None

def render_json(request, obj):
    result = json.dumps(obj, ensure_ascii=False)
    return http.HttpResponse(result, content_type='application/json')

def bad_request(request, obj=None):
    if request.is_ajax():
        return http.HttpResponseBadRequest(json.dumps(obj), content_type='application/json')
    else:
        from django.http import HttpResponseBadRequest
        from django.template import (loader, Context)
        template = loader.get_template('400.html')
        return HttpResponseBadRequest(template.render(Context(obj)))

def not_authorized(request, obj=None):
    return http.HttpResponse(json.dumps(obj), content_type='application/json', status=401)

def permission_denied(request, obj=None):
    if request.is_ajax():
        return http.HttpResponseForbidden(json.dumps(obj), content_type='application/json')
    else:
        from django.core.exceptions import PermissionDenied
        raise PermissionDenied

def not_allowed(request, permitted_methods):
    return http.HttpResponseNotAllowed(permitted_methods)

def not_implemented(request, obj=None):
    return http.HttpResponse(json.dumps(obj), content_type='application/json', status=501)

core/views.py
from django.shortcuts import render
from users.models import *

def index(request):
    team_list = GroupCategory.objects.get(pk=settings.TEAM_GROUPCAT_ID).groups.all()
    context = {
            'teams': filter(lambda x: x in request.user.groups.all(), team_list)
            }

    return render(request, 'index.html', context)

core/templates/core_base.html
{% load staticfiles %}
<!DOCTYPE html>
<!--[if IE 8]> 				 <html class="no-js lt-ie9" lang="{{ LANGUAGE_CODE }}" > <![endif]-->
<!--[if gt IE 8]><!--> <html class="no-js" lang="{{ LANGUAGE_CODE }}" > <!--<![endif]-->

<head>
	<meta charset="utf-8" />
	<title>{% block title %} ‧ SITCON{% endblock %}</title>
	<meta name="description" content="SITCON 學生計算機年會行政系統。關於學生計算機年會，請造訪 http://sitcon.org/。" />
	<meta name="viewport" content="width=device-width" />
	<link rel="stylesheet" href="{% static 'css/app.css' %}" />
	<link rel="shortcut icon" href="{% static 'img/SITCON.ico' %}" />
	<link rel="apple-touch-icon" href="{% static 'img/apple-touch-icon.png' %}" />
	<script src="{% static 'js/vendor/custom.modernizr.js' %}"></script>
</head>
<body>
{% block content_block %}
{% endblock %}

	<script>
	document.write('<script src=' +
	('__proto__' in {} ? '{% static 'js/vendor/zepto.min.js' %}' : '{% static 'js/vendor/jquery.min.js' %}') +
	'><\/script>')
	</script>
	<script src="{% static 'js/vendor/foundation.min.js' %}"></script>
	<script>
	  $(document).foundation();
	</script>
	<script src="{% static 'js/override.js' %}"></script>
{% block scripts %}
{% endblock %}
</body>
</html>

core/templates/core_index.html
{% extends 'core_main.html' %}
{% block title %}SITCON{% endblock %}
{% load usermeta %}
{% block content %}
<div class="row">
	{% if user.is_authenticated %}
	<div class="large-3 columns">
		<img class="avatar large" src="{{ user.email|get_avatar:400 }}" alt="{{ user|get_name }}" />
		<h4>{{ user|get_name }}</h4>
		<h5 class="subheader">{{ user.profile.title }}</h5>
	</div>
	<div class="large-5 columns">
		<h5 class="section-header"><a href="{% url 'issues:assigned' user.id %}">待辦清單</a></h5>
		<ul class="issue-list">
		{% for issue in issues %}
			<li class="issue-entry">
				<div class="issue-id">#{{ issue.id }}</div>
				<h4>
					<span class="issue-icon iconize icon-{% if issue.is_open %}{{ issue.is_expired|yesno:'issue-expired,issue-open' }}{% else %}issue-closed{% endif %}"></span>
					<a href="{% url 'issues:detail' issue.id %}">{{ issue.title }}</a>
					<span class="labels">{% for label in issue.labels.all %}
						<span class="radius label" style="background: #{{ label.color }};">{{ label.name }}</span>
					{% endfor %}</span>
				</h4>
			</li>
		{% endfor %}
		</ul>
	</div>
	<div class="large-4 columns">
		<h5 class="section-header">聚會概覽</h5>
		<p></p>
	</div>
	{% else %}
	<div class="large-6 small-9 small-centered has-quote columns">
		<h3 class="text-center">SITCON 行政系統</h3>
		<p class="quote">
			<p>據說同時是個別名<a href="https://github.com/sitcon-tw/staff.sitcon.org"><abbr title="Roboconf">蘿蔔坑</abbr></a>的開源計劃。</p>
			必須<a href="{% url 'users:login' %}">登入</a>後才能完整使用此系統的所有功能；如果是工作人員，請向行政組索取帳號。<wbr>找的是學生計算機年會的網站？請拜訪 <a href="http://sitcon.org/">SITCON.org</a>。
		</p>
	</div>
	{% endif %}
</div>
{% endblock %}

core/templates/core_main.html
{% extends 'core_base.html' %}
{% load usermeta %}
{% load staticfiles %}
{% block content_block %}
<div class="contain-to-grid fixed">
	<nav class="top-bar">
		<ul class="title-area">
			<li class="name"><h1><a href="/"><span class="logo">SITCON</span></a></h1></li>
			<li class="toggle-topbar menu-icon"><a href="#"><span>功能表</span></a></li>
		</ul>
		<section class="top-bar-section">
			<ul class="left">
				{% if user.is_authenticated %}
				<li><a href="{% url 'docs:main' %}">文件</a></li>
				<li><a href="{% url 'issues:list' %}">待辦事項</a></li>
				<li><a href="#">聚會</a></li>
				<li><a href="{% url 'agenda:main' %}">時間表</a></li>
				<li><a href="{% url 'users:list' %}">人員</a></li>
				{% if perms.notifications.add_message %}
				<li><a href="{% url 'notifications:list' %}">通知</a></li>
				{% endif %}
				{% endif %}
			</ul>
			<ul class="right">
				{% if user.is_authenticated %}
				<li class="has-dropdown">
					<a href="#">
						<img class="avatar small" src="{{ user.email|get_avatar:'#' }}" alt="{{ user|get_name }}" />
						{{ user|get_name }}
					</a>
					<ul class="dropdown">
						<li><label>{{ user.last_name }} {{ user.first_name }}</label></li>
						<li><a href="{% url 'users:edit' user.username %}">帳號設定</a></li>
						{% if user.is_staff %}<li><a href="/backend/">系統設定</a></li>{% endif %}
						<li class="divider"></li>
						<li><a href="{% url 'issues:create' %}">回報問題</a></li>
						<li><a href="{% url 'users:logout' %}">登出</a></li>
					</ul>
				</li>
				{% else %}
				<li><a href="{% url 'users:login' %}">登入</a></li>
				{% endif %}
			</ul>
		</section>
	</nav>
</div>
<div class="container row page-content">
	<div class="large-12 columns">
{% block content %}{% endblock %}
	</div>
</div>
{% endblock %}

core/templates/core_main_safe.html
{% extends 'core_base.html' %}
{% block content_block %}
<div class="contain-to-grid fixed">
	<nav class="top-bar">
		{% spaceless %}
		<ul class="title-area">
			<li class="name"><h1><a href="/"><span class="logo">SITCON</span></a></h1></li>
			<li class="toggle-topbar"><a href="#"><span></span></a></li>
		</ul>
		{# 移除所有元素，以免因 URLConf 炸掉而導致 500 無法顯示 #}
		<section class="top-bar-section">
			<ul class="left"></ul>
			<ul class="right"></ul>
		</section>
		{% endspaceless %}
	</nav>
</div>
<div class="container row page-content">
	<div class="large-12 columns">
{% block content %}{% endblock %}
	</div>
</div>
{% endblock %}

core/templates/index.html
{% extends 'core/master.html' %}
{% block title %}{{ site.name }}{% endblock %}
{% block content %}
<div class="row">
	{% if user.is_authenticated %}
	<div class="large-3 columns">
		<img class="avatar large" src="{{ user.profile.avatar }}" alt="{{ user.profile.name }}" />
		<h4>{{ user.profile.name }}</h4>
		<h5 class="subheader">{% for t in teams %}<span class="radius secondary label" name="{{ t.id }}">{{ t.name }}</span>{% if not forloop.last %} {% endif %}{% endfor %}</h5>
		<ul class="profile-meta">
			{% if user.profile.organization %}<li><span class="icon-school iconize"></span> {{ user.profile.organization }}</li>{% endif %}
			{% if user.profile.phone %}<li><span class="icon-phone iconize"></span> {{ user.profile.phone }}</li>{% endif %}
			{% if user.profile.slack %}<li><span style='display: inline-block; width: 16px; height: 16px; background: url("https://brandfolder.com/api/favicon/icon?size=16&domain=www.slack.com");'></span> <a href="https://coscup.slack.com/messages/@{{ user.profile.slack }}" style="padding-left: 4px;">@{{ user.profile.slack }}</a></li>{% endif %}
			{% if user.email %}<li><span class="icon-email iconize"></span> {{ user.email }}</li>{% endif %}
		</ul>
	</div>
	<div class="large-4 columns">
		<h5 class="section-header">個人介紹</h5>
		<p>{{ user.profile.bio|linebreaks }}</p>
		<ul class="issue-list">
		</ul>
	</div>
	<div class="large-5 columns">
		<h5 class="section-header">個人資料細節</h5>
		<table class="main">
			<!-- TODO icons -->
			<tr>
				<td>姓名</td>
				<td>{{ u.last_name }}{{ u.first_name }}</td>
			</tr>
			<tr>
				<td>年滿 20 歲</td>
				<td>{% if user.profile.twenty %}<span class="icon-checkmark iconize"></span>是{% else %}<span class="icon-cross iconize"</span>否{% endif %}</td>
			</tr>
			<tr>
				<td>曾是工人</td>
				<td>{% if user.profile.prev_worker %}<span class="icon-checkmark iconize"></span>是{% else %}<span class="icon-cross iconize"></span>否{% endif %}</td>
			</tr>
			<tr>
				<td>感謝狀</td>
				<td>{% if user.profile.certificate %}<span class="icon-checkmark iconize"></span>需要{% else %}<span class="icon-cross iconize"></span>不需要{% endif %}</td>
			</tr>
			<tr>
				<td>慶功宴</td>
				<td>{% if user.profile.cel_dinner %}<span class="icon-checkmark iconize"></span>參加{% else %}<span class="icon-cross iconize"></span>不參加{% endif %}</td>
			</tr>
			<tr>
				<td>衣服尺寸</td>
				<td>{{ user.profile.shirt_size }}</td>
			</tr>
			<tr>
				<td>飲食</td>
				<td>{{ user.profile.diet }}</td>
			</tr>
			<tr>
				<td>交通補助</td>
				<td>{% if user.profile.transportation_aid %}需要{% else %}不需要{% endif %}</td>
				{% if user.profile.transportation_aid and user.profile.transportation != "" %}<td>{{ user.profile.transportation }}</td>{% endif %}
			</tr>
			{% if not user.profile.accom == 0 or user.profile.transportation_aid %}
			<tr>
				<td>居住地</td>
				<td>{{ user.profile.residence }}</td>
			</tr>
			<tr>
				<td>住宿</td>
				<td>{% if user.profile.accom == 2 %}需要{% elif user.profile.accom == 1 %}皆可{% else %}不需要{% endif %}</td>
			</tr>
			{% endif %}
			{% if not user.profile.accom == 0 %}
			<tr>
				<td>希望的室友</td>
				<td>{{ user.profile.roommate }}</td>
			</tr>
			<tr>
				<td>性別</td>
				<td>{% if user.profile.gender %}{% if user.profile.gender == 1 %}男{% elif user.profile.gender == 2 %}女{% else %}其他{% endif %}{% endif %}</td>
			</tr>
			{% endif %}
			<tr>
				<td>服務證明</td>
				<td>{% if u.profile.volunteering_proof %}<span class="icon-checkmark iconize"></span>需要{% else %}<span class="icon-cross iconize"></span>不需要{% endif %}</td>
			</tr>
			{% if u.profile.volunteering_proof %}
			<tr>
				<td>出生年月日</td>
				<td>{% if not sensitive %}<span class="has-tip" title="因個資原因隱藏">{{ u.profile.birthday|length }} 位數</span>{% else %}{{ u.profile.birthday }}{% endif %}</td>
			</tr>
			{% endif %}
			<tr>
				<td>備註</td>
				<td>{{ u.profile.comment }}</td>
			</tr>
		</table>
	{% else %}
	<div class="large-6 small-9 small-centered has-quote columns">
		<h3 class="text-center">{{ site.name }}</h3>
		<p class="quote">
			<p>據說同時是個別名<a href="https://github.com/sitcon-tw/roboconf"><abbr title="Roboconf">SITCON 蘿蔔坑</abbr></a>的開源計劃。</p>
			<p>必須<a href="{% url 'users:login' %}">登入</a>後才能開始使用此系統；如果是工作人員，請向行政組索取帳號。</p>
			<p>找的是 COSCUP 的網站？請拜訪 <a href="http://coscup.org/">coscup.org</a>。</p>
		</p>
	</div>
	{% endif %}
</div>
{% endblock %}