agenda/urls.py
from django.conf.urls import patterns, url
from agenda import views

urlpatterns = [
    url(r'^$', views.main, name='main'),
]

api/urls.py
from django.conf.urls import url, include
from api import views
from rest_framework import routers, reverse, response
from rest_framework import views as framework_views

# copied from https://stackoverflow.com/a/23321478/446391
class HybridRouter(routers.DefaultRouter):
    def __init__(self, *args, **kwargs):
        super(HybridRouter, self).__init__(*args, **kwargs)
        self._api_view_urls = {}
    def add_api_view(self, name, url):
        self._api_view_urls[name] = url
    def remove_api_view(self, name):
        del self._api_view_urls[name]
    @property
    def api_view_urls(self):
        ret = {}
        ret.update(self._api_view_urls)
        return ret

    def get_urls(self):
        urls = super(HybridRouter, self).get_urls()
        for api_view_key in self._api_view_urls.keys():
            urls.append(self._api_view_urls[api_view_key])
        return urls

    def get_api_root_view(self):
        # Copy the following block from Default Router
        api_root_dict = {}
        list_name = self.routes[0].name
        for prefix, framework_viewset, basename in self.registry:
            api_root_dict[prefix] = list_name.format(basename=basename)
        api_view_urls = self._api_view_urls

        class APIRoot(framework_views.APIView):
            _ignore_model_permissions = True

            def get(self, request, format=None):
                ret = {}
                for key, url_name in api_root_dict.items():
                    ret[key] = reverse.reverse(url_name, request=request, format=format)
                # In addition to what had been added, now add the APIView urls
                for api_view_key in api_view_urls.keys():
                    ret[api_view_key] = reverse.reverse(api_view_urls[api_view_key].name, request=request, format=format)
                return response.Response(ret)

        return APIRoot.as_view()

# Create a router and register our viewsets with it.
router = HybridRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet, base_name='group')
router.register(r'staffgroups', views.StaffGroupViewSet, base_name='staffgroup')
router.register(r'userprofiles', views.UserProfileViewSet)
router.add_api_view('me', url(r'^me$', views.Me.as_view(), name='me'))

# The API URLs are now determined automatically by the router.
# Additionally, we include the login URLs for the browsable API.
urlpatterns = [
    url(r'^', include(router.urls)),
]

sitconstaff/urls.py
from django.conf.urls import patterns, include, url
from sitconstaff.shortcuts import redirect_static

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'sitconstaff.views.home', name='home'),
    # url(r'^sitconstaff/', include('sitconstaff.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    url(r'^$', 'core.views.index', name='index'),
    url(r'^favicon.ico$', redirect_static('img/SITCON.ico'), name='favicon'),
    url(r'^users$', 'users.views.default'), 
    url(r'^users/', include('users.urls', namespace='users')),
    url(r'^docs/', include('docs.urls', namespace='docs')),
    url(r'^issues/', include('issues.urls', namespace='issues')),
    url(r'^agenda/', include('agenda.urls', namespace='agenda')),
    url(r'^notifications/', include('notifications.urls', namespace='notifications')),
    url(r'^400$', 'django.views.defaults.bad_request'),
    url(r'^403$', 'django.views.defaults.permission_denied'),
    url(r'^404$', 'django.views.defaults.page_not_found'),
    url(r'^500$', 'django.views.defaults.server_error'),
    
    # Uncomment the next line to enable the admin:
    url(r'^backend/', include(admin.site.urls)),
)

users/urls.py
from django.conf.urls import patterns, url
from users import views

urlpatterns = [
    url(r'^$', views.list, name='list'),
    url(r'^reg$', views.reg_list_token, name='reg_list_token'),
    url(r'^reg/add$', views.reg_add_token, name='reg_add_token'),
    url(r'^reg/edit/(?P<token>[0-9A-Za-z]+)$', views.reg_edit_token, name='reg_edit_token'),
    url(r'^reg/form/(?P<token>[0-9A-Za-z]+)$', views.reg_form, name='reg_form'),
    url(r'^login$', views.login, name='login'),
    url(r'^logout$', views.logout, name='logout'),
    url(r'^new$', views.create, name='create'),
    url(r'^contacts$', views.contacts, name='contacts'),
    url(r'^contacts/export(?:/(?P<format>[0-9A-Za-z]+))?$', views.export, name='export'),
    url(r'^password/change$', views.change_password, name='change_password'),
    url(r'^password/reset$', views.reset_password, name='reset_password'),
    url(r'^password/reset/(?P<uidb64>[0-9A-Za-z_\-]+)/(?P<token>[0-9A-Za-z_\-]+)$', views.reset_password_confirm, name='reset_password_confirm'),
    url(r'^me$', views.me, name='me'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)$', views.profile, name='profile'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/edit$', views.edit, name='edit'),
    url(r'^(?P<username>[0-9A-Za-z_@\+\.\-]+)/team/(?P<tid>[0-9]+)$', views.team, name='team'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo$', views.photo.general, name='photo_general'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/small$', views.photo.small, name='photo_small'),
    url(r'^(?P<username_or_pk>[0-9A-Za-z_@\+\.\-]+)/photo/medium$', views.photo.medium, name='photo_medium'),
]

docs/views/view.py
from django.shortcuts import render, redirect
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
from django.http import Http404
from docs.models import File, Permission, BlobText
from docs.perms import get_perms
from docs.utils import parse_nid
from core.formatting import render_document

def view(request, nidb64):
	f = parse_nid(nidb64, File)
	if not f: raise Http404

	perms = get_perms(request.user, f)
	if Permission.VIEW not in perms:
		if request.user.is_authenticated():
			raise PermissionDenied 	# Access forbidden
		else:
			return redirect(reverse('users:login') + ('?next=%s' % reverse('docs:view', args=(nidb64,))))

	text = f.current_revision.text
	if text.format == BlobText.MARKDOWN:
		rendered_text = render_document(text.text)
	elif text.format == BlobText.HTML:
		rendered_text = text
	else: # text.format == BlobText.TEXT:
		rendered_text = r'<blockquote>%s</blockquote>' % text.text

	return render(request, 'docs_view.html', {
		'file': f,
		'text': rendered_text,
		'docperms': {
			'can_edit': Permission.EDIT in perms,
			'can_comment': Permission.COMMENT in perms,
		},
	})

docs/templates/docs_create.html
{% extends 'core_main.html' %}
{% block title %}建立文件{{ block.super }}{% endblock %}
{% block content %}
{% if status %}
<div class="radius {% if status == 'success' %}secondary{% else %}alert{% endif %} alert-box" data-alert>
	{% if status == 'success' %}文件已儲存。
	{% else %}請輸入檔案名稱。{% endif %}
	<a href="#" class="close">&times;</a>
</div>
{% endif %}
<div class="row">
	<div class="large-1 columns">
		<a class="right iconize icon-back has-tip" href="{% url 'docs:view' parent.nid %}" title="回到「{{ parent.name }}」" data-tooltip></a>
	</div>
	<div class="large-8 columns">
		<form action="{% url 'docs:create' %}" method="POST">
		{% csrf_token %}
			<div class="row">
				<div class="large-12 columns">
					<input type="text" name="name" placeholder="名稱" required />
					<input type="hidden" name="at" value="{{ parent.nid }}" />
				</div>
			</div>
			<div class="row">
				<div class="large-6 columns">
					<label for="is_markdown_checkbox"><input type="checkbox" id="is_markdown_checkbox" name="is_markdown" placeholder="名稱" checked /> <span>標記為 Markdown 格式</span></label>
				</div>
				<div class="large-6 columns">
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<textarea name="text" style="min-height: 23em;"></textarea>
				</div>
			</div>
			<div class="button-row">
				<div class="right">
					<input type="submit" class="radius button" name="submit" value="儲存" />
				</div>
			</div>
		</form>
	</div>
	<div class="large-3 columns">
	</div>
</div>
{% endblock %}

docs/templates/docs_file.html
{% extends 'core_main.html' %}
{% block title %}{{ node.name }} ‧ 文件{{ block.super }}{% endblock %}
{% block content %}
{% if status %}
<div class="radius {% if status == 'success' %}secondary{% else %}alert{% endif %} alert-box" data-alert>
	{% if status == 'success' %}文件已儲存。
	{% else %}請輸入檔案名稱。{% endif %}
	<a href="#" class="close">&times;</a>
</div>
{% endif %}
<div class="row">
	<div class="large-1 columns">
		<a class="right iconize icon-back has-tip" href="{% url 'docs:view' node.parent.nid %}" title="回到「{{ node.parent.name }}」" data-tooltip></a>
	</div>
	<div class="large-8 columns">
		<form action="{% url 'docs:view' node.nid %}" method="POST">
		{% csrf_token %}
			<div class="row">
				<div class="large-12 columns">
					<input type="text" name="name" placeholder="名稱" value="{{ node.name }}" {{ docperms.edit|yesno:',disabled' }} required />
				</div>
			</div>
			<div class="row">
				<div class="large-6 columns">
					<label for="is_markdown_checkbox"><input type="checkbox" id="is_markdown_checkbox" name="is_markdown" placeholder="名稱" {% if node.current_revision.text.format == 'M' %}checked{% endif %} {{ docperms.edit|yesno:',disabled' }} /> <span>標記為 Markdown 格式</span></label>
				</div>
				<div class="large-6 columns">
				</div>
			</div>
			<div class="row">
				<div class="large-12 columns">
					<textarea name="text" style="min-height: 23em;" {{ docperms.edit|yesno:',disabled' }}>{{ node.current_revision.text.text }}</textarea>
				</div>
			</div>
			<div class="button-row">
				<div class="right">
					<input type="submit" class="radius button" name="submit" value="儲存" {{ docperms.edit|yesno:',disabled' }} />
				</div>
			</div>
		</form>
	</div>
	<div class="large-3 columns">
		<ul class="side-nav users-actions">
			<li><a href="{% url 'docs:render' node.nid %}"><span class="icon-edit iconize"></span> 檢視文件</a></li>
			{% if docperms.comment %}<li><a href="#"><span class="icon-comment iconize"></span> 附加評論</a></li>{% endif %}
			<li><a href="#"><span class="icon-info iconize"></span> 檢視詳細資訊</a></li>
		</ul>
	</div>
</div>
{% endblock %}

docs/templates/docs_folder.html
{% extends 'core_main.html' %}
{% load usermeta %}
{% load dateutils %}
{% block title %}文件{{ block.super }}{% endblock %}
{% block content %}
<div class="row">
	<div class="large-3 columns main-side-nav">
		<ul class="side-nav filter">
			<li class="active"><a href="{% url 'docs:main' %}">文件</a></li>
			{% if user.is_authenticated %}
			<li><a href="#">星號標記</a></li>
			{% if user.is_staff %}<li><a href="{% url 'docs:view' 'LTFE' %}">垃圾桶</a></li>{% endif %}
			{% endif %}
		</ul>
		<div class="divider"></div>
		{% if node.parent %}
		<div class="treeview">
			<ul>
				{% if docperms.view_parent %}
				<li>
					<a href="{% url 'docs:view' node.parent.nid %}" class="folder">{{ node.parent.name }}</a>
					<ul>
					{% for f in node.parent.folders.all %}
						<li><a href="{% url 'docs:view' f.nid %}" class="folder {% if f.id == node.id %}active{% endif %}">{{ f.name }}</a></li>
					{% endfor %}
					</ul>
				</li>
				{% else %}
				<li><a href="#" class="folder active">{{ node.name }}</a></li>
				{% endif %}
			</ul>
		</div>
		{% endif %}
	</div>
	<div class="large-9 columns">
		<div class="row">
			<div class="large-12 columns button-row">
				<div class="left">
				{% if user.is_authenticated %}
					{% if docperms.edit %}
					<button class="small radius secondary button" title="在「{{ node.name }}」建立新資料夾"><span class="icon-folder iconize"></span></button>
					{% endif %}
					<button class="small radius secondary {{ docperms.edit|yesno:',disabled' }} button" title="共用"><span class="icon-share iconize"></span></button>
					{% if perms.docs.archive %}
					<button class="small radius secondary button" title="封存"><span class="icon-archive iconize"></span></button>
					{% endif %}
					<ul class="radius even-2 button-group">
						<li><button class="small secondary button" title="移動" disabled><span class="icon-move iconize"></span></button></li>
						<li><button class="small secondary button" title="刪除" disabled><span class="icon-delete iconize"></span></button></li>
					</ul>
					<button class="small radius secondary button" title="詳細資訊" disabled><span class="icon-info iconize"></span></button>
				{% endif %}
				</div>
				<div class="right">
					<div>
						<button class="small radius secondary dropdown button" data-dropdown="dropdown-sort">
							<span>排序：</span>標題
						</button>
						<ul id="dropdown-sort" class="f-dropdown" data-dropdown-content>
							<li><a href="#">標題</a></li>
							<li><a href="#">最先更新</a></li>
							<li><a href="#">最晚更新</a></li>
						</ul>
					</div>
					{% if user.is_authenticated %}
					<div>
						<button class="small radius button" href="#" data-dropdown="dropdown-create">建立文件</button>
						<ul id="dropdown-create" class="f-dropdown" data-dropdown-content>
							<li><a href="{% url 'docs:create' %}?at={{ node.nid }}"><span class="icon-new iconize"></span> 新文件</a></li>
							<li><a href="#"><span class="icon-upload iconize"></span> 從電腦上傳</a></li>
							<li><a href="#"><span class="icon-link iconize"></span> 外部連結</a></li>
						</ul>
					</div>
					{% endif %}
				</div>
			</div>
		</div>
		<div class="row">
			<div class="large-12 columns">
				<nav class="breadcrumbs">
				{% if docperms.view_parent %}
				{% for f in node.path %}
					<a href="{% url 'docs:view' f.nid %}" {% if f == folder %}class="current"{% endif %}>{{ f.name }}</a>
				{% endfor %}
				{% else %}
					<a href="#" class="unavailable">文件</a>
					<a href="#" class="current">{{ node.name }}</a>
				{% endif %}
				</nav>
			</div>
		</div>
		<div class="row">
			<div class="large-12 columns">
				{% if node.folders.exists or node.files.exists %}
				<table class="docs-list main">
					<thead>
						<tr>
							<th class="icon-column"><input type="checkbox" data-list-checkbox data-select-all></th>
							<th class="icon-column"></th>
							<th>名稱</th>
							<th class="detail-column">上次修改日期</th>
						</tr>
					</thead>
					<tbody>
					{% for f in node.folders.all %}
						<tr>
							<td class="icon-column"><input type="checkbox" data-list-checkbox data-type="folder" data-id="{{ f.id }}"></td>
							<td class="icon-column"><a href="#" data-list-star data-type="folder" data-id="{{ f.id }}"><span class="icon-star iconize"></span></a></td>
							<td><a href="{% url 'docs:view' f.nid %}"><span class="icon-folder iconize"></span> {{ f.name }}</a></td>
							<td class="detail-column">{{ f.last_modified|smartdate }}</td>
						</tr>
					{% endfor %}
					{% for f in node.files.all %}
						<tr>
							<td class="icon-column"><input type="checkbox" data-list-checkbox data-type="file" data-id="{{ f.id }}"></td>
							<td class="icon-column"><a href="#" data-list-star data-type="file" data-id="{{ f.id }}"><span class="icon-star iconize"></span></a></td>
							<td><a href="{% url 'docs:view' f.nid %}"><span class="icon-file iconize"></span> {{ f.name }}</a></td>
							<td class="detail-column">{{ f.last_modified|smartdate }} {{ f.current_revision.user|get_name }}</td>
						</tr>
					{% endfor %}
					</tbody>
				</table>
				{% else %}
				<div class="placeholder-message">
					<span>尚無文件。{% if user.is_authenticated and docperms.edit %}<a href="{% url 'docs:create' %}?at={{ node.nid }}">建立新文件？</a>{% endif %}</span>
				</div>
				{% endif %}
			</div>
		</div>
	</div>
</div>
{% endblock %}

docs/templates/docs_render.html
{% extends 'core_main_safe.html' %}
{% block title %}{{ node.name }} ‧ 文件{{ block.super }}{% endblock %}
{% block content %}
<div class="left">
	<a class="right iconize icon-back has-tip" href="{% url 'docs:view' node.parent.nid %}" title="回到「{{ node.parent.name }}」" data-tooltip></a>
</div>
<div class="row">
	<div class="large-9 large-centered columns">
		<article>{{ text|safe }}</article>
		<hr />
		<footer>
			<small>本文件由 <a href="http://staff.sitcon.org/">SITCON 行政系統</a>提供。</small>
		</footer>
	</div>
</div>
{% endblock %}